import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/icon";
import { Progress } from "@/components/ui/progress";
import { SourceBadge } from "@/components/shared/chips";
import { MasteryDelta } from "@/components/shared/competency-row";
export const SESSION_ACTIVITIES = ["Preview", "Compreensão", "Recall", "Feedback", "Perguntas", "Exercício", "Revisão"] as const;
export function SessionScript({ current = 0, onDark = false }: { current?: number; onDark?: boolean }) {
  return <ol className="flex flex-col gap-2">{SESSION_ACTIVITIES.map((label, index) => <li key={label} aria-current={index === current ? "step" : undefined} className={`flex items-center gap-3 rounded-[14px] p-3 text-sm ${index === current ? onDark ? "bg-graphite-800 text-white" : "bg-blue-50 text-blue-700" : "text-graphite-500"}`}><span className={`flex h-[28px] w-[28px] shrink-0 items-center justify-center rounded-full font-mono text-xs ${index < current ? "bg-success text-white" : index === current ? "bg-blue-500 text-white" : onDark ? "bg-graphite-800" : "bg-graphite-100"}`}>{index < current ? <Icon name="check" size="inline" /> : index+1}</span><span className="flex-1"><strong className="block font-medium">{label}</strong><small className="font-mono text-xs text-graphite-500">{[5,40,10,5,5,10,5][index]} min</small></span>{index === current && <Icon name="arrow-right" size="inline" />}</li>)}</ol>;
}
export function ActivityPanel({ step, title, children, actions }: { step: string; title: string; children?: ReactNode; actions?: ReactNode }) {
  return <div className="space-y-5"><p className="text-overline font-bold uppercase tracking-[.2em] text-blue-600">{step}</p><h3 className="text-h3 font-bold">{title}</h3>{children}<div className="flex flex-wrap gap-3">{actions}</div></div>;
}
export function PreviewPanel({ objectives, questions }: { objectives: string[]; questions: string[] }) {
  return <div className="space-y-5"><p className="font-mono text-xs text-graphite-400">5 min · leia antes de assistir</p><h4 className="text-overline uppercase tracking-[.18em] text-graphite-400">Você vai conseguir</h4><ul className="space-y-3 text-sm">{objectives.map((item) => <li key={item} className="flex items-start gap-3"><Icon name="checkbox-circle" size="inline" className="shrink-0 text-blue-400" />{item}</li>)}</ul><h4 className="text-overline uppercase tracking-[.18em] text-graphite-400">Perguntas orientadoras</h4><div className="space-y-2">{questions.map((item) => <p key={item} className="rounded-[14px] border border-graphite-700 bg-graphite-800 p-3 text-sm text-white">{item}</p>)}</div><div className="flex flex-wrap gap-2"><SourceBadge name="FAW School" /><SourceBadge name="Blackmagic Training" /></div></div>;
}
export function LessonPanel({ lesson, source, position, progress = 0, companion = true, onOpen, onNote }: { lesson: string; source?: string; position: string; progress?: number; companion?: boolean; onOpen?: () => void; onNote?: () => void }) {
  return <div className="space-y-4 rounded-[16px] border border-graphite-700 bg-graphite-800 p-4 text-white"><div className="flex flex-wrap items-start gap-3"><span className="flex h-[44px] w-[44px] shrink-0 items-center justify-center rounded-[14px] bg-graphite-900 text-blue-400"><Icon name="play-circle" size="nav" /></span><div className="min-w-0 flex-1"><strong className="block text-base">{lesson}</strong><span className="text-xs text-graphite-400">{source}</span></div><span className="whitespace-nowrap font-mono text-xs text-graphite-400">{position}</span></div><Progress value={progress} size="xs" onDark label="Consumo do recurso" /><div className="flex flex-wrap gap-3"><Button size="sm" onClick={onOpen}><Icon name="external-link" size="inline" />Abrir recurso</Button><Button size="sm" variant="ghost" className="text-blue-200 hover:bg-graphite-700" onClick={onNote}><Icon name="add" size="inline" />Nota</Button></div>{companion && <p className="flex items-start gap-2 text-xs text-graphite-400"><Icon name="shield-check" size="inline" className="shrink-0" />O Companion acompanha esta aula e mantém a mesma sessão.</p>}</div>;
}
export function TaskPanel({ brief, checklist, children }: { brief: string; checklist: string[]; children?: ReactNode }) {
  return <div className="space-y-4"><p className="text-sm leading-relaxed">{brief}</p><ul className="list-inside list-disc space-y-2 text-sm text-graphite-600">{checklist.map((item) => <li key={item}>{item}</li>)}</ul>{children}</div>;
}
export function SessionSummary({ title, elapsed, resources, reviewItems }: { title: string; elapsed: string; resources: string[]; reviewItems: number }) {
  return <div className="space-y-5 rounded-xl bg-graphite-900 p-5 text-white"><p className="text-overline font-bold uppercase tracking-[.18em] text-blue-300">Sessão concluída</p><h3 className="text-h3 font-bold">{title}</h3><p className="font-mono text-sm text-graphite-600">{elapsed}</p><ul className="space-y-2 text-sm">{resources.map((resource) => <li key={resource}><Icon name="check" size="inline" /> {resource}</li>)}</ul><div className="grid grid-cols-2 gap-3"><div className="rounded-md bg-graphite-800 p-4"><small className="text-graphite-400">Recall</small><strong className="block font-mono">parcial</strong></div><div className="rounded-md bg-graphite-800 p-4"><small className="text-graphite-400">Perguntas</small><strong className="block font-mono">2 / 3</strong></div></div><MasteryDelta from={52} to={67} /><Progress value={67} onDark /><p className="text-sm">{reviewItems} itens demonstrativos de revisão</p></div>;
}
export function SessionStage({ current, onChange, children, onDark = false, compact = false, header, companion }: { current: number; onChange: (step: number) => void; children: ReactNode; onDark?: boolean; compact?: boolean; header?: ReactNode; companion?: ReactNode }) {
  const surface = onDark ? "rounded-[20px] bg-graphite-900 p-5 text-white" : "rounded-[20px] border border-border bg-surface p-5";
  return <div className={compact ? "flex flex-col gap-5" : "grid items-start gap-5 lg:grid-cols-[260px_minmax(0,1fr)_280px]"}><aside className={`${surface} ${compact ? "order-last" : ""}`}><p className="mb-4 text-overline font-bold uppercase tracking-[.18em] text-graphite-500">Roteiro</p><SessionScript current={current} onDark={onDark} /><div className="mt-5 space-y-2 border-t border-graphite-800 pt-4 text-xs"><p className="text-graphite-500">Sessão pode ser pausada</p><p className="leading-relaxed text-graphite-300">Atividade, recurso, timestamp e notas são mantidos.</p></div></aside><div className={`${surface} space-y-5`}>{header}{children}<div className="flex flex-wrap gap-3">{current > 0 && <Button variant="secondary" size="sm" onClick={() => onChange(current - 1)}>Atividade anterior</Button>}<Button size="sm" aria-label="Próxima atividade" disabled={current === SESSION_ACTIVITIES.length - 1} onClick={() => onChange(current + 1)}>{current === 0 ? "Começar as aulas" : "Próxima atividade"}<Icon name="arrow-right" size="inline" /></Button></div></div>{!compact && companion}</div>;
}
