"use client";
import { useRef, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { MobileShell, MobileSheet } from "@/components/layout/mobile-shell";
import { PageHeader } from "@/components/shared/page-header";
import { SessionCard, SessionRow } from "@/components/shared/session-card";
import { ReviewCard } from "@/components/shared/review-card";
import { PhaseRoute } from "@/components/shared/phase-route";
import { ResourceCard } from "@/components/shared/resource-card";
import { MasteryRing } from "@/components/shared/mastery-ring";
import { CompetencyRow, MasteryDelta } from "@/components/shared/competency-row";
import { CompanionSidebar } from "@/components/shared/companion-sidebar";
import { MediaPlaceholder } from "@/components/shared/media-placeholder";
import { CommandSearch } from "@/components/shared/command-search";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Stepper, Progress } from "@/components/ui/progress";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Badge } from "@/components/ui/badge";
import { Alert } from "@/components/ui/alert";
import { Icon } from "@/components/ui/icon";
import { ProjectChip, StatusChip, SourceBadge, ConfidenceBadge, TimestampChip } from "@/components/shared/chips";
import { MasteryLegend } from "@/components/shared/mastery-legend";
import { EmptyState } from "@/components/shared/empty-state";
import { TimelineItem } from "@/components/shared/timeline-item";
import { DayTile } from "@/components/shared/day-tile";
import { DataTable } from "@/components/shared/data-table/data-table";
import { NoteCard } from "@/components/shared/note-card";
import { LessonList } from "@/components/shared/lesson-list";
import { UploadDropzone, ImportReview } from "@/components/shared/upload-dropzone";
import { FeedbackPanel } from "@/components/shared/feedback-panel";
import { Section } from "./section";
import { LoginDemo } from "./login-demo";
import { EditorDemo, SessionDemo, TableDemo } from "./product-section";
import { REFERENCE_DATA } from "../data/examples";
const SCREENS = ["Hoje","Plano","Biblioteca","Revisar","Progresso","Entrada","Onboarding","Foco","Nota","Detalhe do plano","Resposta"] as const;
type Screen = typeof SCREENS[number];
const DESTINATIONS: Record<string, Screen> = { "/hoje":"Hoje", "/plano":"Plano", "/biblioteca":"Biblioteca", "/revisar":"Revisar", "/progresso":"Progresso" };
function ScreenContent({ screen, mobile = false }: { screen: Screen; mobile?: boolean }) {
  const [answer, setAnswer] = useState("");
  if (screen === "Entrada") return <LoginDemo compact={mobile} />;
  if (screen === "Nota") return <div className="space-y-4"><Button variant="ghost" size="sm">Biblioteca · demonstração</Button><div className={mobile ? "space-y-4" : "grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_280px]"}><div className="space-y-4"><EditorDemo /><div className="flex flex-wrap items-center gap-3"><Button>Salvar nota · demonstração</Button><Button variant="ghost">Cancelar</Button><TimestampChip value="contexto: 30s antes e depois" /></div></div>{!mobile && <aside className="space-y-4"><Card className="space-y-4"><h3 className="text-overline font-bold uppercase tracking-[.18em] text-graphite-600">Origem</h3><div className="flex items-center gap-3"><Icon name="play-circle" size="feature" className="text-blue-600" /><div><strong>Color Spaces · Aula 13</strong><p className="font-mono text-xs text-graphite-600">18:32 / 41:15</p></div></div><Button variant="secondary" size="sm">Abrir no ponto da nota</Button></Card><Card className="space-y-4"><h3 className="text-overline font-bold uppercase tracking-[.18em] text-graphite-600">Integrações · exemplo visual</h3><p className="flex items-center justify-between text-sm">Obsidian<Badge tone="success">Sincronizado</Badge></p><p className="flex items-center justify-between text-sm">Anki<Badge tone="success">1 card gerado</Badge></p><p className="text-xs leading-relaxed text-graphite-600">A nota mantém identidade persistente. Os estados acima são demonstrativos.</p></Card></aside>}</div></div>;
  if (screen === "Foco") return <SessionDemo compact={mobile} />;
  if (screen === "Resposta") return <textarea aria-label="Resposta demonstrativa móvel" placeholder="Reconstrua o que você entendeu." value={answer} onChange={(event) => setAnswer(event.target.value)} className="min-h-[120px] w-full rounded-[14px] border border-graphite-700 bg-graphite-800 p-4 text-[15px] text-white placeholder:text-graphite-400 focus-visible:outline-none focus-visible:shadow-focus" />;
  if (screen === "Onboarding") return <OnboardingComposition mobile={mobile} />;
  if (screen === "Hoje" && mobile) return <div className="space-y-4"><PageHeader title="Hoje" description="Quarta, 09 de setembro · 3 blocos, 18 min de revisão." /><SessionCard {...REFERENCE_DATA.SESSION} activities={REFERENCE_DATA.SESSION.activities.slice(0, 3)} sources={REFERENCE_DATA.SESSION.sources.map((source) => source.name)} /><ReviewCard estimate="18 min" items={[{label:"Flashcards",count:12},{label:"Perguntas abertas",count:3},{label:"Conceito frágil",count:1}]} /><p className="text-overline font-bold uppercase tracking-[.14em] text-graphite-600">Depois de hoje</p><SessionRow time="14:00" project="Inglês" title="Listening" duration="45 min" /><SessionRow time="19:00" project="Audiovisual" title="Montagem" duration="50 min" /><Alert tone="warning" title="Revisão pendente" description="Dois tópicos de Color vencem hoje." /></div>;
  if (screen === "Hoje") return <div className="space-y-5"><PageHeader title="Hoje" description="Quarta, 09 de setembro · 3 blocos planejados, 18 minutos de revisão." /><div className={mobile ? "space-y-4" : "grid gap-5 md:grid-cols-[1.5fr_1fr]"}><div className="space-y-4"><SessionCard {...REFERENCE_DATA.SESSION} sources={REFERENCE_DATA.SESSION.sources.map((source) => source.name)} /><p className="text-overline font-bold uppercase">Depois de hoje</p><SessionRow time="14:00" project="Inglês" title="Listening + produção" duration="45 min" /><SessionRow time="19:00" project="Audiovisual" title="Montagem narrativa" duration="50 min" /></div><div className="space-y-4"><ReviewCard estimate="18 minutos" items={[{label:"Flashcards",count:12},{label:"Perguntas abertas",count:3},{label:"Conceito frágil",count:1}]} /><Card className="space-y-4"><h3 className="text-overline font-bold uppercase">Continuar de onde parou</h3><div className="flex items-center gap-3"><Icon name="play-circle" size="feature" /><div><strong>Color Spaces · Aula 13</strong><p className="font-mono text-xs text-graphite-600">18:32 / 41:15</p></div></div><ProjectChip name="Audiovisual avançado" /></Card><Alert tone="warning" title="Revisão pendente" description="Dois tópicos de Color vencem hoje." />{!mobile && <Card className="space-y-3"><h3 className="text-overline font-bold uppercase">Esta semana</h3><p className="flex justify-between text-sm">Sessões concluídas <span className="font-mono">4 / 7</span></p><p className="flex justify-between text-sm">Tempo estudado <span className="font-mono">5h20 / 8h</span></p><Button variant="ghost" size="sm">Ver progresso · demonstração</Button></Card>}</div></div></div>;
  if (screen === "Plano" || screen === "Detalhe do plano") return <PlanComposition mobile={mobile} detail={screen === "Detalhe do plano"} />;
  if (screen === "Biblioteca") return <LibraryComposition mobile={mobile} />;
  if (screen === "Revisar") return <ReviewComposition mobile={mobile} />;
  return <ProgressComposition mobile={mobile} />;
}
export function CompositionsSection() {
  const [desktop, setDesktop] = useState<Screen>("Hoje");
  const [mobile, setMobile] = useState<Screen>("Hoje");
  const sheetTrigger = useRef<HTMLElement | null>(null);
  const [sheet, setSheet] = useState(false);
  const active = (value: Screen) => value === "Nota" ? "/biblioteca" : value === "Detalhe do plano" ? "/plano" : Object.entries(DESTINATIONS).find(([, name]) => name === value)?.[0] ?? "/hoje";
  return <>
    <Section id="shell" title="12 · Shell" source="templates/app-screen/ · components/layout/"><p className="text-sm">O modelo abaixo reutiliza AppSidebar, Topbar, ProjectSelector, MainContent e PageHeader. As cinco portas permanecem iguais.</p><a href="#composicoes" className="inline-flex items-center text-sm font-semibold text-blue-700">Ver composição interativa</a></Section>
    <Section id="configuracoes" title="16 · Configurações" source="standalone seção 16"><p className="text-xs text-graphite-600">Apresentação da referência visual. Integrações e opções abaixo são exemplos locais, sem habilitar recursos ou definir regras do produto.</p><div className="ds-demo-grid"><Card className="space-y-5"><h3 className="text-overline font-bold uppercase tracking-[.18em] text-graphite-600">Projeto · abas próprias</h3><Tabs defaultValue="Visão geral"><TabsList className="flex flex-wrap">{["Visão geral","Objetivo","Competências","Materiais","Plano","Disponibilidade","Configurações"].map((tab) => <TabsTrigger key={tab} value={tab}>{tab}</TabsTrigger>)}</TabsList></Tabs><div className="grid grid-cols-2 gap-3">{[["Meta","06 dez 2026"],["Tempo","8h/semana"],["Fase","2 de 6"],["Mastery","41%"]].map(([label,value]) => <div key={label} className="rounded-md bg-bg p-4"><span className="block text-xs text-graphite-600">{label}</span><strong>{value}</strong></div>)}</div><div className="flex flex-wrap gap-3"><Button variant="secondary" size="sm">Editar projeto</Button><Button variant="secondary" size="sm">Pausar</Button><Button variant="ghost" size="sm">Alterar prioridade</Button></div><Alert tone="info" title="Editar objetivo, prazo ou materiais pode alterar seu plano." /><Button variant="ghost">Recalcular plano · demonstração</Button></Card><Card className="space-y-5"><h3 className="text-overline font-bold uppercase tracking-[.18em] text-graphite-600">Global · Perfil, Aprendizagem, Agenda, Integrações</h3>{[["Gradum Companion","Instalado"],["Obsidian","Conectado"],["Anki","Conectado"],["Apple Notes","Configurar"]].map(([name,state]) => <div key={name} className="flex items-center justify-between gap-3 text-sm"><span>{name}</span><Badge tone={state === "Configurar" ? "neutral" : "success"}>{state}</Badge></div>)}<div className="space-y-3 border-t border-border pt-4"><h4 className="font-semibold">Flashcards automáticos · copy de referência</h4><RadioGroup defaultValue="sugerir" aria-label="Preferência visual de cards">{[["sugerir","Sugerir cards antes de adicionar"],["auto","Adicionar automaticamente"],["nunca","Nunca gerar"]].map(([value,label]) => <Label key={value} className="flex items-center gap-3"><RadioGroupItem value={value} />{label}</Label>)}</RadioGroup></div><div className="space-y-3 border-t border-border pt-4"><h4 className="font-semibold">Companion captura · exemplo visual</h4>{["Título da aula e posição do player","Legendas disponíveis","Contexto da página"].map((label,index) => <Label key={label} className="flex items-center justify-between gap-3">{label}<Switch defaultChecked={index<2} /></Label>)}<p className="text-xs text-graphite-600">Contexto das notas: 30 segundos antes e depois.</p></div></Card></div></Section>
    <Section id="login" title="18 · Entrada na conta" source="ui_kits/gradum-app/LoginScreen.jsx · contrato F0.3"><LoginDemo /></Section>
    <Section id="composicoes" title="Composições desktop" source="ui_kits/gradum-app/*.jsx · templates/app-screen/"><div role="group" aria-label="Escolher composição desktop" className="flex flex-wrap gap-2">{SCREENS.filter((screen) => screen !== "Resposta").map((screen) => <Button key={screen} variant={desktop === screen ? "tonal" : "ghost"} size="sm" aria-pressed={desktop === screen} onClick={() => setDesktop(screen)}>{screen}</Button>)}</div><p className="text-xs text-graphite-600">Modelo demonstrativo selecionado: {desktop}</p>{["Entrada","Onboarding","Foco"].includes(desktop) ? <ScreenContent key={desktop} screen={desktop} /> : <AppShell active={active(desktop)} onNavigate={(href) => setDesktop(DESTINATIONS[href] ?? "Hoje")}><ScreenContent key={desktop} screen={desktop} /></AppShell>}</Section>
    <Section id="companion" title="Companion" source="ui_kits/gradum-companion/index.html · CompanionSidebar.jsx"><div className="flex flex-col items-stretch gap-5 rounded-xl bg-graphite-100 p-4 md:flex-row md:items-start"><div className="min-w-0 flex-1"><MediaPlaceholder label="Aula externa · exemplo visual" /><p className="mt-4 text-sm text-graphite-600">A aula permanece na plataforma de origem.</p></div><CompanionSidebar session="Exposição e movimento" lesson="Shutter Speed" position="18:32 / 41:15" notes={[{timestamp:"18:32",text:"A regra dos 180° · demonstração"}]} /></div><div className="ds-demo-grid"><Card className="space-y-3"><h3 className="text-overline font-bold uppercase tracking-[.18em]">O que o Companion captura</h3>{["Título da aula e posição do player","Legendas disponíveis","Notas, dúvidas e marcações do usuário"].map((item) => <p key={item} className="flex gap-2 text-sm"><Icon name="check" size="inline" className="shrink-0 text-success" />{item}</p>)}</Card><Card className="space-y-3"><h3 className="text-overline font-bold uppercase tracking-[.18em]">O que ele nunca vira</h3><p className="text-sm leading-relaxed text-graphite-600">Planejamento, mastery, revisão ou um segundo Gradum dentro da aula. Três ações e nada além: Nota, Dúvida, Importante.</p></Card><Card className="space-y-3"><h3 className="text-overline font-bold uppercase tracking-[.18em]">Contexto da nota</h3><div className="flex flex-wrap gap-2"><TimestampChip value="18:32" /><Badge tone="neutral" size="sm">30s antes e depois</Badge></div><p className="text-sm leading-relaxed text-graphite-600">Toda nota volta ao Gradum apontando para a aula, o timestamp e a competência.</p></Card></div></Section>
    <Section id="mobile" title="Composições móveis derivadas" source="ui_kits/gradum-mobile/screens.jsx · MobileShell.jsx"><p className="text-sm text-graphite-600">Onze apresentações derivadas. Moldura iOS é auxiliar; esta vitrine demonstra o conteúdo Gradum.</p><div role="group" aria-label="Escolher composição móvel" className="flex flex-wrap gap-2">{SCREENS.map((screen) => <Button key={screen} variant={mobile === screen ? "tonal" : "ghost"} size="sm" aria-pressed={mobile === screen} onClick={() => setMobile(screen)}>{screen}</Button>)}</div><MobileShell title={mobile} header={!["Entrada","Onboarding","Foco","Resposta","Nota"].includes(mobile)} active={active(mobile)} tabBar={!["Entrada","Onboarding","Foco","Resposta","Nota"].includes(mobile)} onSearch={() => { sheetTrigger.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setSheet(true); }} onNavigate={(href) => setMobile(DESTINATIONS[href] ?? "Hoje")}><ScreenContent key={mobile} screen={mobile} mobile /></MobileShell><MobileSheet onCloseAutoFocus={(event) => { event.preventDefault(); sheetTrigger.current?.focus(); }} open={sheet} onOpenChange={setSheet}><Input aria-label="Buscar no exemplo móvel" /><CommandSearch query="Shutter" groups={[{label:"Notas",results:[{title:"Regra dos 180°"}]}]} /></MobileSheet></Section>
  </>;
}

function DemoTabs({ items, value, onChange }: { items: string[]; value: string; onChange: (value: string) => void }) {
  return <Tabs value={value} onValueChange={onChange}><TabsList>{items.map((item) => <TabsTrigger key={item} value={item}>{item}</TabsTrigger>)}</TabsList></Tabs>;
}
function OnboardingComposition({ mobile }: { mobile: boolean }) {
  const [step, setStep] = useState(0);
  const [target, setTarget] = useState("Profissional");
  const phases = ["Objetivo", "Diagnóstico", "Recursos", "Plano"];
  const actual = mobile && step >= 2 ? step + 1 : step;
  return <div className="mx-auto max-w-[760px] space-y-5">
    <Card padding="md" className="space-y-4"><p className="text-overline uppercase tracking-[.2em] text-graphite-600">Progresso em 4 fases</p><div className="flex flex-wrap gap-3">{phases.map((phase, index) => <span key={phase} className={index === Math.min(step, 3) ? "font-semibold text-blue-600" : "text-graphite-600"}>{phase}</span>)}</div><Stepper current={Math.min(step+1,4)} total={4} /></Card>
    {actual === 0 && <Card className="space-y-5"><h3 className="max-w-[20ch] text-[28px] font-bold leading-tight">O que você quer ser capaz de fazer?</h3><textarea aria-label="Objetivo demonstrativo" className="min-h-[104px] w-full rounded-[14px] border border-graphite-300 p-4" defaultValue="Quero trabalhar profissionalmente como editor audiovisual." /><p className="text-xs text-graphite-600">Exemplos</p><div className="flex flex-wrap gap-2">{["Conversar profissionalmente em inglês","Me tornar desenvolvedor backend","Passar no concurso X"].map((text) => <span key={text} className="rounded-full bg-graphite-100 px-3 py-2 text-xs">{text}</span>)}</div></Card>}
    {actual === 1 && <div className={mobile ? "space-y-4" : "ds-demo-grid"}>{!mobile && <Card className="space-y-4"><p className="text-overline uppercase tracking-[.2em]">Entendi que você quer</p><h3 className="text-[19px] font-bold">Atuar profissionalmente como editor audiovisual</h3>{["Dominar workflow profissional de edição","Desenvolver storytelling","Dominar fundamentos de áudio","Desenvolver color","Construir portfólio"].map((text) => <p key={text} className="text-sm"><Icon name="checkbox-circle" size="inline" /> {text}</p>)}</Card>}<Card className="space-y-4"><h3 className="font-semibold">Meta de domínio</h3><RadioGroup value={target} onValueChange={setTarget}>{[["Proficiência","Consigo executar tarefas guiadas."],["Profissional","Consigo trabalhar sozinho em projetos reais."],["Avançado","Resolvo problemas complexos e decido tecnicamente."],...(!mobile ? [["Especialista","Quero aprofundamento e especialização."]] : [])].map(([title, description]) => <Label key={title} className={`flex items-center gap-3 rounded-[14px] border p-4 ${target === title ? "border-blue-300 bg-blue-50" : "border-border"}`}><RadioGroupItem value={title} /><span><strong className="block">{title}</strong><span className="mt-1 block text-xs font-normal text-graphite-600">{description}</span></span></Label>)}</RadioGroup></Card></div>}
    {actual === 2 && <div className="ds-demo-grid"><Card className="space-y-4"><h3 className="font-semibold">Diagnóstico · mastery graph inicial</h3><div className="flex flex-wrap gap-2">{["Parte 1 · 8 perguntas","Parte 2 · análise","Parte 3 · projeto (opcional)"].map((label) => <Badge key={label}>{label}</Badge>)}</div>{[["Edição",62],["Storytelling",41],["Câmera",36],["Áudio",24],["Color",18]].map(([name, mastery]) => <CompetencyRow key={name} name={String(name)} mastery={Number(mastery)} />)}</Card><Card className="space-y-4 border-[var(--gr-alert-warning-border)]"><p className="text-overline font-bold uppercase">Viabilidade · copy de referência</p><p>De iniciante a domínio profissional em audiovisual, em 3 meses, com 12h por semana.</p><div className="flex gap-3"><div className="rounded-md bg-bg p-4"><small>Disponível</small><strong className="block font-mono">12h/sem</strong></div><div className="rounded-md bg-bg p-4"><small>Total estimado</small><strong className="block font-mono">~144h</strong></div></div><p className="text-sm leading-relaxed">Dá para construir proficiência operacional forte em edição e fundamentos de color e áudio. Domínio avançado em todas as áreas provavelmente exige mais tempo.</p><Label className="flex gap-3 rounded-md border border-blue-200 bg-blue-50 p-4"><RadioGroup defaultValue="focus"><RadioGroupItem value="focus" /></RadioGroup>Priorizar edição profissional</Label></Card></div>}
    {actual === 3 && <Card className="space-y-5"><UploadDropzone /><ImportReview title="FAW School" /><p className="text-sm">371 aulas · 109h15 · 12 áreas · 27 módulos</p><p className="text-sm">Curso → Módulo → Aula · estrutura de recursos</p><div className="flex flex-wrap gap-2">{["duração","nível","professor","software","competências","exercícios"].map((text) => <Badge key={text}>{text}</Badge>)}</div><ConfidenceBadge level="alta" /></Card>}
    {actual === 4 && <div className={mobile ? "space-y-4" : "ds-demo-grid"}><Card className="space-y-5 bg-graphite-900 text-white"><p className="text-overline uppercase tracking-[.2em] text-blue-400">Plano proposto · demonstração</p><h3 className="text-[26px] font-bold">Audiovisual profissional</h3><p className="text-sm text-graphite-300">12 semanas · ~8h/semana · 37 sessões</p>{REFERENCE_DATA.PHASES.map((phase,index) => <div key={phase.title} className="flex gap-3 rounded-md bg-graphite-800 p-3"><span className="font-mono text-blue-400">{index+1}</span>{phase.title}</div>)}<p className="text-sm">78% do plano usa materiais que você já possui</p><Progress value={78} onDark /></Card>{!mobile && <Card className="space-y-4"><h3 className="font-semibold">Resumo final</h3>{[["Objetivo","Editor audiovisual profissional"],["Prazo","3 meses · 06 dez 2026"],["Nível atual","Iniciante/intermediário"],["Tempo","8h/semana"],["Prioridade","Principal"],["Conteúdo principal","FAW School"],["Fases","6"]].map(([label,value]) => <div key={label} className="flex justify-between gap-3 text-sm"><span className="text-graphite-600">{label}</span><span>{value}</span></div>)}<Alert tone="success" title="Seu projeto está pronto" description="Copy de referência · primeira fase: Fundamentos · primeira sessão amanhã, 07:00 · 75 min" /></Card>}</div>}
    <div className="flex justify-between gap-3"><Button variant="secondary" disabled={step===0} onClick={() => setStep(step-1)}>Voltar</Button><Button onClick={() => setStep(step === (mobile ? 3 : 4) ? 0 : step+1)}>{actual === 4 ? "Reiniciar apresentação" : "Continuar"}</Button></div>
  </div>;
}
function PlanComposition({ mobile, detail = false }: { mobile: boolean; detail?: boolean }) {
  const [planId,setPlanId] = useState<string | null>(detail ? "av" : null);
  const [tab,setTab] = useState("Visão geral");
  const plan = REFERENCE_DATA.PLANS.find((item) => item.id === planId);
  if (!plan) return <div className="space-y-5">{!mobile && <PageHeader title="Plano" description="Cada projeto tem uma rota própria. Seu tempo é global." action={<Button size="sm">Novo plano · demonstração</Button>} />}<div className={mobile ? "space-y-4" : "ds-demo-grid"}>{REFERENCE_DATA.PLANS.map((item) => <Card key={item.id} className="space-y-4"><div className="flex justify-between gap-3"><ProjectChip name={item.project} color={item.color} /><StatusChip status={item.status === "pausado" ? "pausado" : "ativo"} /></div><h3 className="text-[18px] font-bold">{item.name}</h3><p className="flex justify-between text-xs"><span>{mobile ? `Fase ${item.phase} · ${item.hours}` : "Mastery"}</span><span className="shrink-0 whitespace-nowrap font-mono">{item.mastery}%</span></p><Progress value={item.mastery} label="Mastery" tone={item.status === "pausado" ? "soft" : "action"} />{!mobile && <div className="grid grid-cols-2 gap-3">{[["Fase",item.phase],["Tempo",item.hours],["Prioridade",item.priority],["Meta",item.deadline]].map(([label,value]) => <div key={label} className="rounded-md bg-bg p-3"><span className="block text-xs text-graphite-600">{label}</span><strong className="text-sm">{value}</strong></div>)}</div>}<Button variant="secondary" size="sm" onClick={() => setPlanId(item.id)}>Abrir plano</Button></Card>)}</div>{!mobile && <Card className="space-y-4"><h3 className="text-overline font-bold uppercase">Divisão do seu tempo · 12h por semana</h3>{REFERENCE_DATA.PLANS.map((item) => <div key={item.id} className="space-y-2"><p className="flex justify-between text-sm"><span>{item.project} · {item.priority}</span><span className="font-mono">{item.hours}</span></p><Progress value={item.share} /></div>)}</Card>}</div>;
  return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={() => setPlanId(null)}>Voltar aos planos</Button>{mobile ? <h3 className="text-[18px] font-bold leading-snug">{plan.name}</h3> : <PageHeader title={plan.name} description={plan.goal} />}{mobile && <div className="flex gap-3"><ProjectChip name={plan.project} color={plan.color} /><StatusChip status={plan.status === "pausado" ? "pausado" : "ativo"} /></div>}<div className="flex flex-wrap gap-3"><Button variant="secondary" size="sm">Editar plano · demonstração</Button>{!mobile && <Button variant="secondary" size="sm">{plan.status === "pausado" ? "Retomar" : "Pausar"} · demonstração</Button>}</div>{!mobile && <div className="grid grid-cols-2 gap-3 md:grid-cols-3">{[["Estado",plan.status],["Fase",plan.phase],["Tempo",plan.hours],["Prioridade",plan.priority],["Meta",plan.deadline],["Mastery",plan.mastery+"%"]].map(([label,value]) => <div key={label} className="rounded-md border border-border bg-surface p-4"><span className="block text-xs text-graphite-600">{label}</span><strong className="text-sm">{value}</strong></div>)}</div>}<DemoTabs items={mobile ? ["Visão geral","Semana","Fases"] : ["Visão geral","Semana","Calendário","Fases"]} value={tab} onChange={setTab} />
    {tab === "Visão geral" && <div className={mobile ? "space-y-4" : "ds-demo-grid"}><Card className="space-y-4"><h3 className="font-semibold">Objetivo e meta de domínio</h3><strong>{plan.goal}</strong><p className="text-sm">{plan.target}</p>{!mobile && <div className="flex flex-wrap gap-2">{plan.sources.map((source) => <SourceBadge key={source} name={source} />)}</div>}</Card><Card className="space-y-4"><MasteryRing value={plan.mastery} /><p className="text-sm">{plan.sessions} sessões em {plan.weeks} semanas · fase {plan.phase}</p></Card><Card className="space-y-4"><h3 className="font-semibold">Fase atual · {plan.currentPhase.title}</h3><p className="text-sm">{plan.currentPhase.note}</p><p className="font-mono text-sm">{plan.currentPhase.remaining} · {plan.currentPhase.hours} · {plan.currentPhase.targetMastery}</p></Card>{!mobile && <Alert tone={plan.status === "pausado" ? "warning" : "info"} title={plan.status === "pausado" ? "Plano pausado" : "Plano recalculado ontem"} description="Copy de referência. Apresentação visual sem alteração de regra de agendamento." />}</div>}
    {tab === "Semana" && (plan.week.length ? <div className="space-y-4">{plan.week.map((day) => <TimelineItem key={day.day} day={day.day} entries={day.entries.map((entry) => ({ time:entry.time,project:entry.title,title:entry.subtitle,duration:entry.duration }))} />)}</div> : <EmptyState title="Nenhuma sessão nesta semana" description="Este plano demonstrativo está pausado." />)}
    {tab === "Calendário" && <Card className="space-y-4"><h3 className="font-semibold">Setembro · {plan.name}</h3><div className="grid grid-cols-7 gap-2">{Array.from({length:28},(_,i) => <DayTile key={i} day="" date={String(i+1)} state={plan.calendar.includes(i+1) ? "planned" : "empty"} />)}</div></Card>}
    {tab === "Fases" && <div className={mobile ? "space-y-4" : "ds-demo-grid"}><PhaseRoute phases={plan.phases.map((phase,index) => ({index:index+1,title:phase.title,state:phase.state === "atual" ? "atual" : phase.state === "concluida" ? "concluida" : "futura",mastery:phase.mastery}))} />{!mobile && <div className="ds-table"><DataTable queryKey={["demo-phases",plan.id]} endpoint="" localData={{rows:plan.phaseRows}} descriptor={{columns:[{key:"phase",header:"Fase"},{key:"sessions",header:"Sessões",align:"right"},{key:"mastery",header:"Mastery",align:"right"}]}} /></div>}</div>}
  </div>;
}
function LibraryComposition({ mobile }: { mobile: boolean }) {
  const [tab,setTab] = useState("Cursos");
  const [query,setQuery] = useState("");
  const [adding,setAdding] = useState(false);
  return <div className="space-y-5"><PageHeader title="Biblioteca" description="Tudo que você já tem, organizado para aprender." action={<Button size="sm" onClick={() => setAdding(!adding)}>Adicionar material</Button>} />{adding && <UploadDropzone onChoose={() => setAdding(false)} />}<div className="flex flex-wrap items-center gap-3"><DemoTabs items={mobile ? ["Cursos","Documentos","Notas"] : ["Cursos","Documentos","Aulas","Notas","Tabela"]} value={tab} onChange={setTab} /><Input aria-label="Buscar materiais demonstrativos" placeholder="Buscar materiais…" className="max-w-[240px]" value={query} onChange={(event) => setQuery(event.target.value)} /></div>
    {tab === "Cursos" && <><div className={mobile ? "space-y-4" : "ds-demo-grid"}>{REFERENCE_DATA.RESOURCES.filter((item) => item.kind === "curso" && item.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map((item) => <ResourceCard key={item.title} kind="curso" title={item.title} meta={item.meta} progress={item.progress} badges={item.tags} project={item.project} />)}</div>{!mobile && <Card className="space-y-4"><h3 className="font-semibold">Detalhe de curso · FAW School</h3><div className="flex flex-wrap gap-3"><SourceBadge name="FAW School" /><ConfidenceBadge level="alta" /></div><LessonList lessons={[{title:"Aula 11 · Exposição",duration:"32 min",state:"concluida"},{title:"Aula 12 · Latitude",duration:"28 min",state:"concluida"},{title:"Aula 13 · Color Spaces",duration:"41 min",state:"atual"},{title:"Aula 14 · Curvas log",duration:"36 min",state:"bloqueada"}]} /></Card>}</>}
    {tab === "Documentos" && <><ResourceCard kind="documento" title="Camera Fundamentals.pdf" meta="Documento · 42 páginas" /><EmptyState title="Arraste mais materiais" description="PDF, DOCX, PPTX, CSV, TXT e transcrições." /><Button variant="tonal">Adicionar material · demonstração</Button></>}
    {tab === "Aulas" && <LessonList lessons={[{title:"Aula 09 · Shutter Speed",duration:"18 min",state:"concluida"},{title:"Aula 13 · Color Spaces",duration:"41 min",state:"atual"},{title:"Aula 14 · Curvas log",duration:"36 min",state:"bloqueada"}]} />}
    {tab === "Notas" && <div className={mobile ? "space-y-4" : "ds-demo-grid"}>{REFERENCE_DATA.NOTES.map((note) => <NoteCard key={note.title} {...note} kind={note.kind === "duvida" ? "duvida" : note.kind === "importante" ? "importante" : "nota"} />)}</div>}
    {tab === "Tabela" && <TableDemo />}
  </div>;
}
function ReviewComposition({ mobile }: { mobile: boolean }) {
  const [index,setIndex] = useState(0);
  const [answered,setAnswered] = useState(false);
  const [answer,setAnswer] = useState("");
  const item=REFERENCE_DATA.REVIEW_ITEMS[index];
  const next=()=>{setIndex(index+1);setAnswered(false);setAnswer("");};
  return <div className="space-y-5"><PageHeader title="Revisar" description="16 itens agendados para hoje · 18 minutos · todos os projetos" />{!item ? <Card className="space-y-4"><h3 className="text-h3 font-bold">Revisão concluída</h3><MasteryDelta from={51} to={67} /><Button variant="secondary" onClick={()=>setIndex(0)}>Revisar de novo</Button></Card> : <div className={mobile ? "space-y-4" : "ds-demo-grid"}><Card className="space-y-5"><div className="flex flex-wrap gap-3"><Badge tone="brand">{item.kind}</Badge><span className="text-xs text-graphite-600">{item.meta}</span><span className="font-mono text-xs">{index+1} / {REFERENCE_DATA.REVIEW_ITEMS.length}</span></div><Progress value={(index+(answered?1:0))/REFERENCE_DATA.REVIEW_ITEMS.length*100} /><h3 className="text-h3 font-bold">{item.prompt}</h3>{answered ? <FeedbackPanel title="Quase lá" points={["Você descreveu o gamut corretamente.","Faltou dizer quando Display P3 é obrigatório na entrega."]} /> : <textarea aria-label="Resposta de revisão demonstrativa" value={answer} onChange={(event)=>setAnswer(event.target.value)} placeholder="Sem consultar suas notas…" className="min-h-[120px] w-full rounded-[14px] border border-graphite-300 p-4" />}<div className="flex flex-wrap gap-3">{answered ? <Button onClick={next}>Próximo item</Button> : <><Button onClick={()=>setAnswered(true)}>Enviar resposta</Button><Button variant="secondary" onClick={()=>setAnswered(true)}>Responder falando</Button><Button variant="ghost" onClick={next}>Pular</Button></>}</div></Card>{!mobile && <Card className="space-y-4"><h3 className="font-semibold">Fila de hoje</h3>{REFERENCE_DATA.REVIEW_ITEMS.map((entry,i)=><div key={entry.prompt} className="flex gap-3 text-sm"><Icon name={i<index?"check":"focus-3"} /><div>{entry.kind}<p className="text-xs text-graphite-600">{entry.meta}</p></div></div>)}</Card>}</div>}</div>;
}
function ProgressComposition({ mobile }: { mobile: boolean }) {
  const [tab,setTab] = useState("Projeto");
  return <div className="space-y-5"><PageHeader title="Progresso" description="Mastery vem de evidências: recall, exercícios, projetos e retenção." />{!mobile && <DemoTabs items={["Projeto","Todos os projetos"]} value={tab} onChange={setTab} />}{tab === "Todos os projetos" ? <div className="ds-table"><DataTable queryKey={["demo-all-projects"]} endpoint="" localData={{rows:REFERENCE_DATA.PLANS}} descriptor={{columns:[{key:"project",header:"Projeto"},{key:"status",header:"Estado"},{key:"phase",header:"Fase"},{key:"hours",header:"Tempo/semana"},{key:"mastery",header:"Mastery",align:"right"}]}} /></div> : <div className={mobile ? "space-y-4" : "grid min-w-0 gap-5 xl:grid-cols-2"}><Card className="space-y-5"><MasteryRing value={61} segments={[{label:"Dominado",value:61,color:"var(--gr-action)"},{label:"Em prática",value:27,color:"var(--gr-blue-200)"},{label:"Não iniciado",value:12,color:"var(--gr-graphite-200)"}]} /><MasteryLegend items={[{label:"Dominado",value:"14 competências",color:"var(--gr-action)"},{label:"Em prática",value:"6 competências",color:"var(--gr-blue-200)"},{label:"Não iniciado",value:"3 competências",color:"var(--gr-graphite-200)"}]} /></Card><Card className="space-y-4"><h3 className="font-semibold">Competências · Audiovisual profissional</h3>{REFERENCE_DATA.COMPETENCIES.map((item)=><CompetencyRow key={item.name} {...item} />)}<MasteryDelta from={51} to={61} /></Card><Card className="space-y-4"><h3 className="font-semibold">Retenção</h3><p className="flex justify-between text-sm"><span>Itens mantidos após 30 dias</span><span className="font-mono">82%</span></p><Progress value={82} /><p className="text-sm">Conceitos frágeis em acompanhamento · 3</p></Card><Card className="space-y-4"><h3 className="font-semibold">Evidências recentes</h3>{[["Recall livre · Color Spaces","parcial"],["Exercício · Correção de exposição","correto"],["Pergunta aberta · Shutter 1/50","correto"],["Projeto · Curta de 60s","em avaliação"]].map(([label,verdict])=><p key={label} className="flex flex-wrap justify-between gap-3 text-sm"><span>{label}</span><strong className="whitespace-nowrap text-blue-700">{verdict}</strong></p>)}</Card></div>}</div>;
}
