"use client";
import { useEffectiveTokens } from "./token-section";
import { GradumLogo } from "@/components/shared/gradum-logo";
import { GradumMark } from "@/components/shared/companion-sidebar";
import { Icon } from "@/components/ui/icon";
import { Card } from "@/components/ui/card";
import { Section } from "./section";
import { ICONS } from "../data/examples";
export function FoundationsSection() {
  const tokens = useEffectiveTokens();
  const value = (name: string) => tokens.find((token) => token.name === `--gr-${name}`)?.value ?? "…";
  return <>
    <Section id="marca" title="01 · Marca" source="assets/ · guidelines/brand-*"><div className="ds-demo-grid"><Card className="space-y-5"><GradumLogo size={56} /><GradumMark size={64} /><p>Your path to mastery</p></Card><Card className="space-y-5 bg-graphite-900 text-white"><GradumLogo tone="dark" size={56} /><GradumMark tone="dark" size={64} /><p>Small steps. Big futures.</p></Card></div><div className="ds-demo-grid">{[["Símbolo","Duas folhas em progressão: a inferior clara é o ponto de partida, a superior sólida é a maestria. Respiro mínimo: altura da folha menor."],["Assinatura horizontal","Uso padrão em headers, e-mails e documentos. Espaço entre símbolo e wordmark: 40% da largura do símbolo."],["Fundo escuro","Sobre Graphite 900, a folha clara vira contorno. Nunca aplicar logo colorido sobre fotos sem overlay."]].map(([title,description]) => <div key={title} className="space-y-2"><strong>{title}</strong><p className="text-sm text-graphite-600">{description}</p></div>)}</div><p className="text-sm">A more capable you, for a brighter tomorrow.</p><p className="text-sm text-graphite-600">Variantes fornecidas. Minimal · Calm · Precise · Intelligent.</p></Section>
    <Section id="cor" title="02 · Cor" source="tokens/colors.css · guidelines/colors-*"><div className="ds-demo-grid">{[["Primary","Deep Graphite","text"],["Brand/Action","Mist Blue","action"],["Background","Soft Ivory","bg-app"],["Text Secondary","Cool Gray","text-secondary"],["Accent Light","Ice Blue","action-soft"],["Surface","White","surface"]].map(([role,name,color]) => <Card key={role} className="space-y-3"><div className="h-[64px] rounded-md border border-border" style={{background:`var(--gr-${color})`}} /><span className="text-xs text-graphite-600">{role}</span><strong className="block">{name}</strong><span className="font-mono text-xs">{value(color)}</span></Card>)}</div><div className="ds-demo-grid">{["graphite", "blue"].map((scale) => <div key={scale} className="space-y-2">{[50,100,200,300,400,500,600,700,800,900].map((step) => <div key={step} className="flex items-center gap-3"><span className="h-10 flex-1 rounded-sm" style={{ background: `var(--gr-${scale}-${step})` }} /><span className="w-[110px] font-mono text-xs">{scale} {step}</span></div>)}</div>)}</div><div className="ds-demo-grid">{["bg","bg-app","surface","success","warning","danger","info","success-soft","warning-soft","danger-soft"].map((token) => <div key={token} className="rounded-md border border-border p-4"><div className="mb-3 h-12 rounded-sm" style={{ background: `var(--gr-${token})` }} /><span className="font-mono text-xs">--gr-{token}</span></div>)}</div><p className="text-sm text-graphite-600">Azul identifica ação, seleção e progresso. Texto azul usa 600/700 em superfícies claras.</p></Section>
    <Section id="tipografia" title="03 · Tipografia" source="tokens/fonts.css · typography.css · guidelines/type-*"><p className="font-sans text-h3">Plus Jakarta Sans · Aa Bb Cc 0123</p><p className="font-mono text-h3">JetBrains Mono · 67% · 1h15</p><div className="flex flex-wrap gap-5">{[300,400,500,600,700,800].map((weight) => <span key={weight} style={{fontWeight:weight}}>Aa · {weight}</span>)}</div><div className="space-y-5">{["display","h1","h2","h3","body-lg","body","sm","overline"].map((name) => <div key={name} style={{ fontSize: `var(--gr-text-${name}-size)`, lineHeight: `var(--gr-text-${name}-lh)`, fontWeight: `var(--gr-text-${name}-weight)`, letterSpacing: `var(--gr-text-${name}-tracking)` }}>Aprender com clareza <span className="text-xs text-graphite-600">{name}</span></div>)}</div><p className="text-sm">Produto: título {value("app-page-title")} · seção {value("app-section-title")} · card {value("app-card-title")} · corpo {value("app-body")} · metadado {value("app-metadata")}.</p></Section>
    <Section id="espaco" title="04 · Espaço, raio e elevação" source="tokens/spacing, radius, elevation, layout e motion"><div className="flex flex-wrap items-end gap-4">{[1,2,3,4,5,6,7,8].map((step) => <div key={step} className="text-center"><div className="bg-blue-200" style={{ width: `var(--gr-space-${step})`, height: `var(--gr-space-${step})` }} /><span className="font-mono text-xs">{value(`space-${step}`)}</span></div>)}</div><div className="flex flex-wrap gap-4">{["sm","md","lg","xl","2xl","full"].map((size) => <div key={size} className="border border-blue-200 bg-blue-50 p-5" style={{ borderRadius: `var(--gr-radius-${size})` }}>{size} · {value(`radius-${size}`)}</div>)}</div><div className="ds-demo-grid">{["sm","md","lg","action"].map((level) => <Card key={level} style={{ boxShadow: `var(--gr-shadow-${level})` }}>Elevação {level}</Card>)}</div><div className="grid grid-cols-12 gap-2">{Array.from({ length: 12 }, (_, index) => <span key={index} className="h-12 rounded-sm bg-blue-100" />)}</div><p className="text-sm">{value("grid-columns")} colunas · gutter {value("gutter")} · máximo {value("shell-max")} · breakpoints {["sm","md","lg","xl"].map((size) => value(`bp-${size}`)).join(" / ")}. Movimento {["fast","base","slow"].map((speed) => value(`duration-${speed}`)).join(" / ")}; redução respeitada.</p></Section>
    <Section id="iconografia" title="10 · Iconografia" source="guidelines/icons-* · components/core/Icon.jsx"><div className="flex flex-wrap gap-5">{ICONS.map((name) => <span key={name} className="flex w-[90px] flex-col items-center gap-2 text-center text-xs text-graphite-600"><Icon name={name} size="nav" />{name}</span>)}</div><div className="flex flex-wrap gap-5">{(["inline","control","nav","feature"] as const).map((size) => <span key={size}><Icon name="sun" size={size} /> {size}</span>)}<Icon name="sun" variant="fill" size="nav" /><Icon name="bold" variant="none" /></div></Section>
    <Section id="arquitetura" title="11 · Arquitetura da informação" source="standalone seção 11"><p className="text-h3 font-semibold">Projeto → Fases → Plano → Sessões → Atividades → Recursos</p><p className="text-sm">Hoje · Plano · Biblioteca · Revisar · Progresso</p><p className="text-sm text-graphite-600">Biblioteca é o que existe. Plano é o que foi escolhido para estudar agora.</p><Card className="space-y-3"><strong>Fora da navegação principal</strong><div className="flex flex-wrap gap-3">{["Onboarding","Sessão de estudo","Companion","Busca global","Gerenciar projetos","Detalhe de curso","Detalhe de fase"].map((label) => <span key={label} className="rounded-full bg-graphite-100 px-3 py-2 text-xs">{label}</span>)}</div></Card></Section>
    <Section id="principios" title="14 · Princípios" source="guidelines/brand-anti-patterns.html · standalone seção 14"><div className="ds-demo-grid">{[["Background","var(--gr-bg-app)"],["Surface","var(--gr-surface)"],["Elevated","var(--gr-surface)"]].map(([label,color],index) => <div key={label} className="rounded-xl border border-border p-6" style={{background:color,boxShadow:index===2?"var(--gr-shadow-md)":undefined}}>{label}</div>)}</div><div className="ds-demo-grid"><Card className="space-y-4"><strong>Card agrupa, não decora</strong><div className="flex justify-between border-b border-border pb-3 text-sm"><span>Color Spaces</span><span>52%</span></div><p className="text-sm text-success">Correto: linha simples dentro de um card único.</p></Card><Card className="space-y-4"><Card className="flex justify-between text-sm"><span>Color Spaces</span><span>52%</span></Card><p className="text-sm text-danger">Evitar: um card por competência.</p></Card></div><div className="ds-demo-grid"><Card><strong>Um conceito por superfície</strong><p className="mt-3 text-sm">Linhas simples agrupam competências e recursos.</p></Card><Card><strong>Domínio por evidência</strong><p className="mt-3 text-sm">Consumo de conteúdo não demonstra domínio.</p></Card><Card><strong>Recompensa discreta</strong><p className="mt-3 text-sm">Progresso de domínio, sem confete ou pontos.</p></Card></div></Section>
    <Section id="niveis" title="17 · Três níveis do produto" source="standalone seção 17"><div className="ds-demo-grid">{[["Conta","Quem sou e quanto tempo tenho?","Disponibilidade, preferências, integrações. Configuração global."],["Projeto","O que quero dominar e com quais recursos?","Objetivo, diagnóstico, materiais, prazo, competências e prioridade."],["Aprendizagem","O que faço agora para chegar lá?","Sessões, recall, exercícios, revisão e mastery."]].map(([level,title,description]) => <Card key={level} className="space-y-3"><p className="text-overline font-bold uppercase tracking-[.18em] text-graphite-600">{level}</p><strong className="block text-[17px]">{title}</strong><p className="text-sm leading-relaxed text-graphite-600">{description}</p></Card>)}</div><pre className="overflow-x-auto rounded-xl bg-graphite-100 p-5 font-mono text-xs leading-loose">{"USER · disponibilidade, preferências, integrações\n↓\nPROJECT · objetivo, prazo, prioridade, target mastery\n↓\nUSER STATE · nível inicial, mastery graph\n↓\nRESOURCES · cursos, materiais, documentos, links\n↓\nCOMPETENCY · competências necessárias\n↓\nGAP ANALYSIS · o que falta\n↓\nCURRICULUM · fases e sessões\n↓\nSCHEDULER · distribuição no tempo"}</pre><p className="text-sm text-graphite-600">Copy de referência. Hoje, Plano, Revisar e Progresso apresentam consequências desses dados.</p></Section>
  </>;
}
